const DB_NAME='g2-sheet-music',SCORES='scores',FOLDERS='folders',VERSION=3
function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(SCORES)){const s=d.createObjectStore(SCORES,{keyPath:'id'});s.createIndex('createdAt','createdAt')}if(!d.objectStoreNames.contains(FOLDERS)){const f=d.createObjectStore(FOLDERS,{keyPath:'id'});f.createIndex('createdAt','createdAt')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function saveScore(record){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(SCORES,'readwrite');tx.objectStore(SCORES).put(record);tx.oncomplete=()=>resolve(record);tx.onerror=()=>reject(tx.error)})}
export async function listScores(){const d=await db();return new Promise((resolve,reject)=>{const req=d.transaction(SCORES,'readonly').objectStore(SCORES).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)));req.onerror=()=>reject(req.error)})}
export async function getScore(id){const d=await db();return new Promise((resolve,reject)=>{const req=d.transaction(SCORES,'readonly').objectStore(SCORES).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
export async function deleteScore(id){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(SCORES,'readwrite');tx.objectStore(SCORES).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function moveScoreToFolder(id,folderId=null){const r=await getScore(id);if(!r)return null;r.folderId=folderId||null;r.updatedAt=Date.now();await saveScore(r);return r}
export async function createFolder(name){name=String(name||'').trim();if(!name)throw new Error('Bitte einen Ordnernamen eingeben.');const d=await db(),record={id:globalThis.crypto?.randomUUID?.()||`folder-${Date.now()}-${Math.random().toString(36).slice(2)}`,name,createdAt:Date.now(),updatedAt:Date.now()};return new Promise((resolve,reject)=>{const tx=d.transaction(FOLDERS,'readwrite');tx.objectStore(FOLDERS).put(record);tx.oncomplete=()=>resolve(record);tx.onerror=()=>reject(tx.error)})}
export async function listFolders(){const d=await db();return new Promise((resolve,reject)=>{const req=d.transaction(FOLDERS,'readonly').objectStore(FOLDERS).getAll();req.onsuccess=()=>resolve((req.result||[]).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'de')));req.onerror=()=>reject(req.error)})}
export async function fileToStored(file){return {name:file.name,type:file.type,lastModified:file.lastModified||0,bytes:await file.arrayBuffer()}}
export function storedToFile(stored){if(!stored)return null;try{return new File([stored.bytes],stored.name||'score',{type:stored.type||'',lastModified:stored.lastModified||Date.now()})}catch{return new Blob([stored.bytes],{type:stored.type||''})}}
